coverage:
  ignore: #things we ignore
    # In travis we are only building the latest
    - "src/main/pre-2.0/.*"
    - "src/main/pre-2.2/.*"
    - "src/main/1.3-only/.*"
    - "src/main/pre-1.5/.*"
    - "src/test/.*"