/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.holdenkarau.spark.testing

import java.time.Duration

import scala.collection.JavaConverters._

import org.apache.spark.sql.{DataFrame, Row, SparkSession}
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.json4s._
import org.json4s.jackson.Serialization
import org.json4s.jackson.JsonMethods._

case class ColumnMismatch(smth: String) extends Exception(smth)

/**
 * DataFrame assertions written against nothing but the DataFrame API.
 *
 * Everything in here compiles against classic spark-sql *and* against the
 * Spark Connect client, which is why it lives in its own source directory
 * shared by both builds -- nothing here touches RDDs, SparkContext,
 * SQLContext or catalyst internals.
 *
 * [[DataFrameSuiteBaseLike]] mixes this in and adds the RDD-based helpers on
 * top; the Connect-only suite bases mix it in as-is.
 */
trait DataFrameAssertionsLike extends TestSuiteLike {

  val maxUnequalRowsToShow = 10

  /** The session the assertions run against. */
  def spark: SparkSession

  /**
   * Compare if two schemas are equal, ignoring __autoGeneratedAlias magic
   */
  def assertSchemasEqual(expected: StructType, result: StructType): Unit = {
    def dropInternal(s: StructField) = {
      // No metadata no need to filter
      val metadata = s.metadata
      if (!metadata.contains("__autoGeneratedAlias")) {
        s
      } else {
        val jsonString = metadata.json
        val metadataMap = (parse(jsonString).values.asInstanceOf[Map[String, Any]] - "__autoGeneratedAlias")
        implicit val formats = org.json4s.DefaultFormats
        val cleanedJson = Serialization.write(metadataMap)
        val cleanedMetadata = org.apache.spark.sql.types.Metadata.fromJson(cleanedJson)
        new StructField(s.name, s.dataType, s.nullable, cleanedMetadata)
      }
    }
    val cleanExpected = expected.iterator.map(dropInternal).toList
    val cleanResult = result.iterator.map(dropInternal).toList
    assert(cleanExpected, cleanResult)
  }

  /**
   * Compares if two [[DataFrame]]s are equal, checks the schema and then if that
   * matches checks if the rows are equal.
    *
    * @param customShow unit function to customize the '''show''' method
    *                   when dataframes are not equal. IE: '''df.show(false)''' or
    *                   '''df.toJSON.show(false)'''.
   */
  def assertDataFrameEquals(expected: DataFrame, result: DataFrame,
                            customShow: DataFrame => Unit = _.show()): Unit = {
    assertDataFrameApproximateEquals(expected, result, 0.0,
      Duration.ZERO, customShow)
  }

  /**
   * Compare if two columns in the same DataFrame are equal.
   */
  def assertColumnEquality(
    df: DataFrame,
    colName1: String,
    colName2: String
  ): Unit = {
    // `=!=` yields NULL when either side is NULL and filter drops the row, so
    // (NULL, 1) would compare equal. `<=>` is the null-safe comparison.
    val elements = df.select(colName1, colName2)
      .filter(not(col(colName1) <=> col(colName2)))
      .collect()
    val colName1Elements = elements.map(_(0))
    val colName2Elements = elements.map(_(1))
    val mismatchMessage = s"""
Columns aren't equal
'$colName1' elements:
[${colName1Elements.mkString(", ")}]
'$colName2' elements:
[${colName2Elements.mkString(", ")}]
"""
    if (!colName1Elements.sameElements(colName2Elements)) {
      throw ColumnMismatch(mismatchMessage)
    }
  }

  /**
    * Compares if two [[DataFrame]]s are equal, checks that the schemas are the same.
    * When comparing inexact fields uses tol.
    *
    * @param tol max acceptable tolerance for numeric (between(0, 1)) &
    *            timestamp (millis).
    */
  @deprecated(
    "Use `assertDataFrameApproximateEquals` with timestamp tolerance",
    since = "1.5.0"
  )
  def assertDataFrameApproximateEquals(expected: DataFrame, result: DataFrame,
                                       tol: Double): Unit =
    assertDataFrameApproximateEquals(expected, result, tol,
      Duration.ofMillis(tol.toLong), _.show())

  /**
    * Compares if two [[DataFrame]]s are equal without caring about order of rows, by
    * finding elements in one DataFrame that is not in the other. The resulting
    * DataFrame should be empty inferring the two DataFrames have the same elements.
    * Also verifies that the schema is identical.
    */
  def assertDataFrameNoOrderEquals(expected: DataFrame, result: DataFrame) {
    assertSchemasEqual(expected.schema, result.schema)
    assertDataFrameDataEquals(expected, result)
  }


  /**
   * Compares if two [[DataFrame]]s are equal without caring about order of rows, by
   * finding elements in one DataFrame that is not in the other. The resulting
   * DataFrame should be empty inferring the two DataFrames have the same elements.
   * Does not compare the schema.
   */
  def assertDataFrameDataEquals(expected: DataFrame, result: DataFrame): Unit = {
    val expectedCol = "assertDataFrameNoOrderEquals_expected"
    val actualCol = "assertDataFrameNoOrderEquals_actual"
    val expectedPostMap = convertMapToArrayStruct(expected)
    val resultPostMap = convertMapToArrayStruct(result)
    try {
      expected.cache()
      result.cache()
      assert("Column size not Equal", expected.columns.size, result.columns.size)
      assert("Length not Equal", expected.count(), result.count())

      val keyColumns = expectedPostMap.columns
      val expectedElementsCount = expectedPostMap
        .groupBy(keyColumns.map(col): _*)
        .agg(count(lit(1)).as(expectedCol))
      val resultElementsCount = resultPostMap
        .groupBy(keyColumns.map(col): _*)
        .agg(count(lit(1)).as(actualCol))

      // Rename the right hand side before joining. Joining on identically
      // named columns leaves the result carrying each key twice, and Spark
      // Connect ships results as Arrow, whose deserializer looks fields up by
      // name and fails with AMBIGUOUS_COLUMN_OR_FIELD. Renaming keeps the key
      // values visible in the failure output either way.
      // Widen the suffix until the renamed columns cannot collide with an
      // existing one -- a frame carrying both `foo` and `foo__result` would
      // otherwise reintroduce the very ambiguity this rename exists to avoid.
      val existing = keyColumns.toSet
      val suffix = Iterator.iterate("__result")(_ + "_")
        .find(s => keyColumns.forall(name => !existing.contains(name + s)))
        .get
      val resultNames = keyColumns.map(name => name + suffix)
      val resultRenamed = resultElementsCount.toDF((resultNames :+ actualCol): _*)

      val joinExprs = keyColumns.zip(resultNames).map {
        case (expectedName, resultName) =>
          expectedElementsCount.col(expectedName) <=> resultRenamed.col(resultName)
      }.reduce(_.and(_))

      val diff = expectedElementsCount
        .join(resultRenamed, joinExprs, "full_outer")
        .filter(not(col(expectedCol) <=> col(actualCol)))

      assertEmpty(diff.take(maxUnequalRowsToShow))
    } finally {
      expected.unpersist()
      result.unpersist()
    }
  }

  /**
    * Converts map-typed columns into array-of-struct columns so that [[DataFrame]]s
    * containing maps can be compared reliably in tests.
    *
    * Spark does not define a stable ordering for values of map type, which means that
    * operations used in test assertions (such as set-like comparisons that ignore
    * row order) cannot directly rely on map columns being orderable. This helper
    * normalizes map columns into an orderable representation before comparison.
    *
    * For each map column, this method produces an array of structs created by
    * zipping the map keys and values via `arrays_zip(map_keys(col), map_values(col))`.
    * In the resulting struct, field `"0"` holds the key and field `"1"` holds the
    * corresponding value. Non-map columns are preserved as-is.
    *
    * The transformation is applied recursively to nested structures: maps inside
    * structs, arrays of structs containing maps, and other combinations are all
    * rewritten so that every map encountered in the schema is converted to an
    * array of structs in this way.
    *
    * The method is marked `private[testing]` because it is an internal utility of
    * the testing framework, intended to support DataFrame equality checks rather
    * than to be part of the public API.
    */
  private[testing] def convertMapToArrayStruct(df: DataFrame): DataFrame = {
    def buildExpr(dataType: DataType, colName: String): String = dataType match {
      case MapType(_, _, _) =>
        s"arrays_zip(map_keys($colName), map_values($colName)) AS $colName"
      case StructType(fields) =>
        val inner = fields.map { f =>
          s"'${f.name}', ${buildExpr(f.dataType, s"$colName.${f.name}").replaceAll(" AS .*", "")}"
        }.mkString(", ")
        s"named_struct($inner) AS $colName"
      case ArrayType(elementType, _) =>
        elementType match {
          case MapType(_, _, _) =>
            val mapExpr =
              s"arrays_zip(map_keys(x), map_values(x))"
            s"flatten(transform($colName, x -> $mapExpr)) AS $colName"
          case StructType(fields) =>
            val structExpr =
              fields.map(f =>
                s"'${f.name}', ${buildExpr(f.dataType, s"x.${f.name}").replaceAll(" AS .*", "")}"
              ).mkString(", ")
            s"transform($colName, x -> named_struct($structExpr)) AS $colName"
          case _ =>
            val inner = buildExpr(elementType, "x").replaceAll(" AS .*", "")
            s"transform($colName, x -> $inner) AS $colName"
        }
      case _ =>
        s"$colName"
    }

    val exprs = df.schema.fields.map(f => buildExpr(f.dataType, f.name))
    df.selectExpr(exprs: _*)
  }

  /**
   * Compares if two [[DataFrame]]s are equal without caring about order of rows, by
   * finding elements in one DataFrame that is not in the other.
   * Similar to the function assertDataFrameDataEquals but for small [[DataFrame]]
   * that can be collected in memory for the comparison.
   */
  def assertSmallDataFrameDataEquals(
    expected: DataFrame, result: DataFrame): Unit = {

    val cols = expected.columns
    assert("Column size not Equal", cols.size, result.columns.size)
    assertTrue(expected.collect.toSet ==
      result.select(cols.head, cols.tail: _*).collect.toSet)
  }

  def approxEquals(r1: Row, r2: Row, tol: Double): Boolean = {
    RowComparisons.approxEquals(r1, r2, tol, Duration.ofMillis(tol.toLong))
  }

  def approxEquals(r1: Row, r2: Row, tolTimestamp: Duration): Boolean = {
    RowComparisons.approxEquals(r1, r2, tolTimestamp)
  }

  def approxEquals(r1: Row, r2: Row, tol: Double,
                   tolTimestamp: Duration): Boolean = {
    RowComparisons.approxEquals(r1, r2, tol, tolTimestamp)
  }

  /**
   * Compare collected rows rather than joining the underlying RDDs by index.
   *
   * This is what [[assertDataFrameApproximateEquals]] does by default, and
   * what the Connect suites use, since Connect has no RDDs. The classic
   * suite bases override the public method with an RDD-based version that
   * can render mismatches without pulling everything to the driver.
   */
  protected def assertDataFrameApproximateEqualsCollected(
      expected: DataFrame, result: DataFrame,
      tol: Double, tolTimestamp: Duration,
      customShow: DataFrame => Unit): Unit = {
    try {
      expected.cache()
      result.cache()
      assertSchemasEqual(expected.schema, result.schema)

      val expectedRows = expected.collect()
      val resultRows = result.collect()

      assert("Length not Equal", expectedRows.length.toLong, resultRows.length.toLong)

      val unequalRows = expectedRows.zip(resultRows).zipWithIndex.filter {
        case ((r1, r2), _) =>
          !(r1.equals(r2) || RowComparisons.approxEquals(r1, r2, tol, tolTimestamp))
      }

      if (unequalRows.nonEmpty) {
        val sample = unequalRows.take(maxUnequalRowsToShow)
        val unequalSchema = StructType(
          StructField("source_dataframe", StringType) ::
            expected.schema.fields.toList)
        // Row.fromSeq rather than the classic path's GenericRowWithSchema:
        // catalyst is not on the classpath when this file is compiled against
        // the Spark Connect client.
        val taggedRows = sample.flatMap { case ((r1, r2), _) =>
          Seq(Row.fromSeq("expected" +: r1.toSeq),
            Row.fromSeq("result" +: r2.toSeq))
        }.toList.asJava
        customShow(spark.createDataFrame(taggedRows, unequalSchema))
        val message = sample.map { case ((r1, r2), idx) =>
          s"Row $idx: expected=$r1, actual=$r2"
        }.mkString("\n")
        fail(s"There are some unequal rows:\n$message")
      }
    } finally {
      expected.unpersist()
      result.unpersist()
    }
  }

  /**
   * Compares if two [[DataFrame]]s are equal, checks that the schemas are the
   * same. When comparing inexact fields uses tol & tolTimestamp.
   */
  def assertDataFrameApproximateEquals(
      expected: DataFrame, result: DataFrame,
      tol: Double, tolTimestamp: Duration,
      customShow: DataFrame => Unit = _.show()): Unit =
    assertDataFrameApproximateEqualsCollected(
      expected, result, tol, tolTimestamp, customShow)
}
